### ISSUE TITLE
HTTPS 配置后，启动nginx报错

### ISSUE THREAD

**Issue by yangmqit** [chatopera/cskefu#439]
已经参考 https://github.com/chatopera/cskefu/issues/414

配置好后，单独启动服务可以正常访问，启动nginx后无法访问，报错：
contact-center_1  | 2021-04-26 19:50:20.926 WARN  o.h.e.j.spi.SqlExceptionHelper - SQL Error: 0, SQLState: null [http-nio-8035-exec-20] 
contact-center_1  | 2021-04-26 19:50:20.926 ERROR o.h.e.j.spi.SqlExceptionHelper - wait millis 60000, active 100, maxActive 100 [http-nio-8035-exec-20] 
contact-center_1  | 2021-04-26 19:50:20.927 ERROR o.a.c.c.C.[.[.[.[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.orm.jpa.JpaSystemException: Unable to acquire JDBC Connection; nested exception is org.hibernate.exception.GenericJDBCException: Unable to acquire JDBC Connection] with root cause [http-nio-8035-exec-20] 

![image](https://user-images.githubusercontent.com/26617650/116078349-1079ff00-a6c9-11eb-9927-bd97e30bac79.png)

**Comment by yangmqit** [comment]
开了 nginx 就连不上，nginx 配置了 https，关掉 nginx 访问 http://ip:8035 是正常的

**Comment by hailiang-wang** [comment]
nginx 的配置是什么样的？
配置 nginx 的过程是也是看了文档?
https://chatopera.blog.csdn.net/article/details/105820829

**Comment by yangmqit** [comment]
是的，看了文档

-----------------------
.env
------
```
# https://docs.docker.com/compose/reference/envvars/#compose_file
# for Enterprise edition: docker-compose.yml:./private/docker-compose.ext.yml
COMPOSE_FILE=docker-compose.yml
COMPOSE_PROJECT_NAME=cpmskefu

# OS Params
## for Enterprise edition: dockerhub.qingcloud.com/chatopera/contact-center:tag
CC_IMAGE=chatopera/contact-center:develop
SWITCH_IMAGE=dockerhub.qingcloud.com/chatopera/switch:develop
CC_JAVA_XMX=12288m
CC_JAVA_XMS=2048m

# Variables
MYSQL_PORT=8037
REDIS_PORT=8041
ES_PORT1=8039
ES_PORT2=8040
CC_WEB_PORT=8035
#CC_SOCKET_PORT=8036
CC_SOCKET_PORT=443
ACTIVEMQ_PORT1=8051
ACTIVEMQ_PORT2=8052
ACTIVEMQ_PORT3=8053
DB_PASSWD=cpmc7788945passQ
LOG_LEVEL=INFO

## chatbot
## https://docs.chatopera.com/products/cskefu/work-chatbot.html
BOT_THRESHOLD_FAQ_BEST_REPLY=0.8
BOT_THRESHOLD_FAQ_SUGG_REPLY=0.6

TONGJI_BAIDU_SITEKEY=placeholder
ADS_LOGIN_BANNER=off
```
---------------------------------------------
docker-compose.yml
---------
```
version: "3"
services:
  nginx:
    image: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/logs:/var/log/nginx
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/certs:/certs
    depends_on:
      - contact-center

  contact-center:
    image: ${CC_IMAGE:-chatopera/contact-center:develop}
    restart: always
    ports:
      - "${CC_WEB_PORT:-8035}:8035"
      #- "${CC_SOCKET_PORT:-8036}:8036"
    volumes:
      - ./contact-center/data:/data
      - ./contact-center/logs:/logs
    environment:
      - "JAVA_OPTS=-Xmx${CC_JAVA_XMX:-12288m} -Xms${CC_JAVA_XMS:-2048m} -XX:PermSize=256m -XX:MaxPermSize=1024m -Djava.net.preferIPv4Stack=true"
      - SERVER_PORT=8035
      - SERVER_LOG_PATH=/logs
      - SERVER_LOG_LEVEL=${LOG_LEVEL:-WARN}
      - WEB_UPLOAD_PATH=/data
      - SPRING_DATA_ELASTICSEARCH_PROPERTIES_PATH_DATA=/data
      - UK_IM_SERVER_PORT=8036
      - UK_IM_SERVER_HOST=localhost
      - UK_IM_SERVER_THREADS=10
      # set a separated port for SSL
      - CS_IM_SERVER_SSL_PORT=${CC_SOCKET_PORT:-8036}
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/cosinee?useUnicode=true&characterEncoding=UTF-8
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWD:-123456}
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
      - SPRING_REDIS_PASSWORD=${DB_PASSWD:-123456}
      - SPRING_DATA_ELASTICSEARCH_CLUSTER_NAME=elasticsearch
      - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
      - SPRING_ACTIVEMQ_BROKER_URL=tcp://activemq:61616
      - CSKEFU_MODULE_CALLOUT=false
      - CSKEFU_MODULE_CONTACTS=true
      - CSKEFU_MODULE_CHATBOT=true
      - SKYPE_CHANNEL_CRM=${SKYPE_CHANNEL_CRM:-placeholder}
      - BOT_THRESHOLD_FAQ_BEST_REPLY=${BOT_THRESHOLD_FAQ_BEST_REPLY:-0.9}
      - BOT_THRESHOLD_FAQ_SUGG_REPLY=${BOT_THRESHOLD_FAQ_SUGG_REPLY:-0.3}
      - CSKEFU_SETTINGS_WEBIM_VISITOR_SEPARATE=true
      - TONGJI_BAIDU_SITEKEY=${TONGJI_BAIDU_SITEKEY:-placeholder}
      - ADS_LOGIN_BANNER=${ADS_LOGIN_BANNER:-off}
    depends_on:
      - mysql
      - redis
      - elasticsearch
      - activemq

  activemq:
    image: chatopera/activemq:5.14.3
    restart: always
    environment:
      - ACTIVEMQ_ADMIN_LOGIN=admin
      - ACTIVEMQ_ADMIN_PASSWORD=${DB_PASSWD:-123456}
      - ACTIVEMQ_ENABLED_SCHEDULER=true
      - ACTIVEMQ_MIN_MEMORY=1024
      - ACTIVEMQ_MAX_MEMORY=4096
    volumes:
      - ./database/activemq/data:/data
      - ./database/activemq/logs:/var/log/activemq
    ports:
      - "${ACTIVEMQ_PORT1:-8051}:8161"
      - "${ACTIVEMQ_PORT2:-8052}:61616"
      - "${ACTIVEMQ_PORT3:-8053}:61613"

  mysql:
    image: chatopera/mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWD:-123456}
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=${DB_PASSWD:-123456}
    ports:
      - "${MYSQL_PORT:-8037}:3306"
    volumes:
      - ./database/mysql/data:/var/lib/mysql
    command: --max_allowed_packet=32505856

  redis:
    image: chatopera/redis:5.0.5
    environment:
      - REDIS_PASSWORD=${DB_PASSWD:-123456}
    restart: always
    volumes:
      - ./database/redis/data:/data
    ports:
      - "${REDIS_PORT:-8041}:6379"

  elasticsearch:
    image: elasticsearch:2.4.6
    restart: always
    volumes:
      - ./database/elasticsearch/data:/usr/share/elasticsearch/data
      - ./database/elasticsearch/config:/usr/share/elasticsearch/config
      - ./database/elasticsearch/plugins:/usr/share/elasticsearch/plugins
    ports:
      - "${ES_PORT1:-8039}:9200"
      - "${ES_PORT2:-8040}:9300"
```
------------------------------------
default.conf
------------
```
server{
    #listen 80; 
    listen 443 ssl;
    server_name kefu.***.com;
    root /usr/share/nginx/html;
    client_max_body_size 100M;

    ssl_certificate /certs/**.com.pem;
    ssl_certificate_key /certs/**.com.key;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers HIGH:!aNULL:!MD5;



    location / {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass http://contact-center:8035; 
    }

    location /actuator {
	return 403 "403: Target API is blocked.";

    }

    location /socket.io { 
    	proxy_set_header Upgrade $http_upgrade;
    	proxy_set_header Connection "Upgrade";
	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	proxy_set_header Host $host;
	proxy_http_version 1.1;
	proxy_pass http://contact-center:8036; 
    }
}

```
